server:
  port: 8081
  servlet:
    context-path: /AppName

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/realDb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: realUser
    password: realPass
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: detect
  application:
    name: AppName
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @environment@

logging.level.root: INFO

ro:
  marius:
    cirstea:
      properties:
        jwtSecret: w41t4s3c0nd
        jwtExpiration: 21600