server:
  port: 8081
  servlet:
    context-path: /EventTracker

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eventtracker
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: marius
    password: OP3L45TR4
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: detect
  application:
    name: EventTracker
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @environment@

logging.level.root: INFO

ro:
  marius:
    cirstea:
      properties:
        jwtSecret: eventTrackerS3cr3t
        jwtExpiration: 21600