server:
  port: 8081
  servlet:
    context-path: /Template

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/yourDb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yourUser
    password: yourPass
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: detect
  application:
    name: Template
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @environment@

logging.level.root: INFO

ro:
  marius:
    cirstea:
      properties:
        jwtSecret: t3mpl4t353cr3t
        jwtExpiration: 21600